
name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Test Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/third_practice
          cd /home/ubuntu/third_practice

          # clone if not exists
          if [ ! -d ".git" ]; then
          git clone https://github.com/AsadGulzar/third_practice.git .
          fi

          git pull origin main

          # setup venv
          python3 -m venv venv
          source venv/bin/activate

          pip install -r requirements.txt
          
          sudo systemctl restart myapp

          # restart app
      
